### ISSUE TITLE
Libtinfo issues on Arch based systems

### ISSUE THREAD

**Issue by PlayerW** [GrimKriegor/TES3MP-deploy#4]
The log:
https://pastebin.com/jYiGT8dB

This is a more appropriate place for this issue

**Comment by GrimKriegor** [comment]
Thanks a lot, I was just about to move it here.

Should be fixed now. https://github.com/GrimKriegor/TES3MP-deploy/commit/b00084d2921142a4262c8e132e19cec5399e4e3a

Please test and report back.

You will have to run the installation again, unfortunately.

    ./tes3mp-deploy.sh --install

**Comment by PlayerW** [comment]
Seems to work! (I like that message at the end too, lol)
Browser is installed properly, too! I noticed I couldn't join any game, so I used the 
./tes3mp-deploy.sh --upgrade
command but it still won't work. Figured it might be because of your fix? Or am I missing something?

**Comment by GrimKriegor** [comment]
Ahahah, glad you liked the message.

Yes, not being able to join a game is expected, most servers on the list are builds of the latest stable version (0.6.0) and most Windows users, if not all are also using that version.

You will have to build a slightly older commit, like so:

    ./tes3mp-deploy.sh --rebuild --commit f61664ff6d521e10db761a550c97c6edce8f0046 --version-string 0.6.0

Anyway, feel free to join us in our [Discord "server"](https://discord.gg/emPMkNv). Hate to promote non-free platforms but it's where the party is at.

**Comment by PlayerW** [comment]
Thank you! Everything works now, joined a 0.6.0 server and it runs great!
Sorry for taking so much of your time, though :)
And sure, I'll join the Discord

**Comment by GrimKriegor** [comment]
No problem sera, glad to help. 
See you on the other side and thanks for reporting.
